# Site
name: 'Donkey Travel Productions'
description: 'Donkey Travel Productions is personal blog about traveling the globe.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
# baseurl: '/mundana-theme-jekyll'
baseurl: ''
disqus: 'donkeytravel'
email: 'itheologitou@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
formspree: xgevveaw #create account in https://formspree.io

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    irene:
      name:           Irene
      site:           https://donkeytravel.github.io
      avatar:         /assets/images/avatar3.jpg
      bio:            "Hi, I am Irene, the author of Travel Donkey, the blog you're currently viewing. I hope you like it!"
      email:          itheologitou@gmail.com
      twitter:        https://twitter.com/donkeytravel

    kyr:
      name:           Kyriakos
      site:           https://enlighting.eu
      avatar:         /assets/images/avatar1.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          kyr@designisdesign.eu
      twitter:        https://twitter.com/coralisigns
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: irene
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
